import React from "react";
import LandingNavbar from "../LandingNavbar/LandingNavbar";
import { useHistory } from "react-router-dom";
import "./landing.css";
import EmailWizard from "../EmailWizard/EmailWizard";
import { signInWithGoogle } from "../Login/firebase";
import { useState } from "react";
const Landing = () => {
  const history = useHistory();
  const [user, setUser] = useState("");
  const buttonClickHandler = () => {
    signInWithGoogle();
    const login = localStorage.getItem("email");
    setUser(login);
  };
  return (
    <>
      {user && history.push("/home")}
      <div className="landing">
        <LandingNavbar onLogin={buttonClickHandler} />
        <div className="heading">
          Our AI email writer personalizes in seconds
        </div>
        <div className="subheading1">
          Sky rocket your cold emails with unique personalizations generated by
          AI
        </div>
        <div className="glow-on-hover">
          <span
            className="buttonText"
            type="button"
            onClick={buttonClickHandler}
          >
            Try AI Email Writer now
          </span>
        </div>
        <div className="backgroundImage">
          <img src="https://warmer.ai/step3.png" alt="" />
        </div>
        <div className="startAI">
          <div className="left">
            <div className="startHeading">
              Start Generating AI Emails Today{" "}
            </div>
            <div className="subheadingPush">PUSHING THE ENVELOPE OF EMAIL</div>
            <button className="signUp">Yes! Sign Up Now</button>
          </div>
          <div className="right">
            <img
              src="https://cdn.devdojo.com/images/september2020/cta-1.png"
              alt=""
              className="excited"
            />
          </div>
        </div>
        <div className="seeItInAction">
          <div className="left">
            <div className="inActionText">See It In Action</div>
          </div>
          <div className="right">
            <div className="modal">
              <div className="leftModal">
                <img src="https://i.pravatar.cc/400?img=52" alt="" />
              </div>
              <div className="rightModal">
                <span className="rightModalText">
                  Sam - loved your blog post on taking Bieber's album to over
                  200m streams, he's been on an absolute roll this year.
                </span>
                <span className="author">
                  Sam Cooper -{" "}
                  <span className="place">Marketing at Universal Records</span>
                </span>
              </div>
            </div>
            <div className="modal">
              <div className="leftModal">
                <img src="https://i.pravatar.cc/400?img=9" alt="" />
              </div>
              <div className="rightModal">
                <span className="rightModalText">
                  Fascinating to see your case study on increasing event
                  attendance - using SMS to drive signups is super smart!
                </span>
                <span className="author">
                  Jess Bright -{" "}
                  <span className="place">Head of Growth at TicketMaster</span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Landing;
